language: node_js

cache: yarn

sudo: false

addons:
  firefox: "49.0"

notifications:
  email: false

node_js:
  - '7'

branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"

before_install:
  - export CHROME_BIN=chromium-browser

before_script:
  - npm prune

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start